### ISSUE TITLE
Braille doesn't work properly

### ISSUE THREAD

**Issue by yilinxia** [xability/maidr-legacy#112]
- when braille is on, can not open help menu. Not sure if this is solvable
- the cursor not working anymore for several graphs

**Comment by jooyoungseo** [comment]
Good point! I am assigning this to @yujuny2 to further investigate.

**Comment by jooyoungseo** [comment]
> the cursor not working anymore for several graphs 

@yilinxia Would you mind providing some reproducible steps for @yujuny2?

**Comment by yujuny2** [comment]
@yilinxia @jooyoungseo I have enabled help menu toggle in braille. However this means that for now I need to disable the functionality of auto turn off braille mode when it is out of focus because braille will be auto turned off if we toggle the help menu. It might cause some confusion on which section the user is on if I do not do so. I think further discussion should be done on when we should auto turn off the braille mode so that the users can use them easily because sometimes I'll find it weird too to have my braille mode suddenly turned off even when I did not press the B key to turn it off.

@yilinxia Could you provide me with some reproducible steps for the cursor problem? I have tested it and I couldn't find which part has gone wrong. Thanks.

**Comment by yilinxia** [comment]
@yujuny2 Yeah, I think the cursor somehow get fixed. Regarding enabling help menu in the braille, do you mean after we press the help menu, if users want to press left right, the bralle wont give any feedback?

**Comment by yujuny2** [comment]
@yilinxia No, what I mean is that with the auto-turn-off-braille functionality enabled, when you toggle the help menu in the braille input, the focus changes from the braille to the menu. And because of that the braille will get turned off automatically. When you toggle off the help menu, your current focus will be svg rather than braille, which is where you toggled on the help menu.

**Comment by yilinxia** [comment]
@yujuny2 Oh great point! When testing, I found if I close the help menu, the braille part is still being highlighted. Not sure if the focus is still on braille. But we should ask help from @jooyoungseo to test it on braille display and see if it works.

**Comment by jooyoungseo** [comment]
@yujuny2 -- Thanks for pointing this out! I understand that we need to take a tradeoff. We need to go back to the original behavior then: disabling help menu in braille mode and turn off braille when it loses its focus. We need to automatically turn off braille against focusOut event as originally designed; otherwise, it would cause some side effects that against SVG object's application role and I can further explain this in the meeting. Anyway, in summary, @yujuny2 -- please kindly put back the original behavior, and close this issue once it's done.
