### ISSUE TITLE
Boxplot: Ctrl+Shift+Up/DownArrows does not work in braille mode in Edge

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#151]
1. On Windows, open task 3 boxplot (horizontal) in MS Edge.

1. Press tab to focus in the SVG area.

1. Press B to activate braille and S for sonification.

1. Press Ctrl+Shift+Down/UpArrows to autoplay vertically in braille mode.

* Note: this does not work while the same behavior works in Edge for heatmap.

**Comment by yujuny2** [comment]
@jooyoungseo I think this applies to boxplot because the user needs to select a box/element before turning on Braille mode. There is a line of text to remind the user to do so before turning on Braille mode -- "Please select a box before turning on Braille mode."

As for heatmap, I've tried it on Edge and fixed the issue. However I realized that the audio for the last row is not working on Edge. I tried Chrome and Safari and both are working. I'm sure that there's no obvious bug in the code. Can you double check it to identify whether it is a browser problem? Thanks.
