### ISSUE TITLE
Sonification bug: Ctrl+Home plays double-tone when braille mode is on

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#157]
1. Open any graphs.

1. Turn on both sonification and braille mode.

1. Press Ctrl+Home and Ctrl+End: These are played as double-tones.

**Comment by ellvix** [comment]
@jooyoungseo can't reproduce. On bar and heat I hear only 1 tone. On scatter there are lots. On boxplot yeah I hear multiple outliers but that's what's in the data: 3 outliers at the start of tutorial, and lots (like 7?) at the end of task. Null sound has 2 tones by design, but after we tweaked audio duration maybe it doesn't sound good anymore and we need to readjust and set a constant interval.
