### ISSUE TITLE
Boxplot cursor location is not preserved

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#25]
In boxplot, changing group refreshes the cursor location, defaulting to min area instead of preserving the current stat area. For example, if the current cursor is at 25% of group A, users may expect to land in 25% of group B when they press down arrow key.

**Comment by ellvix** [comment]
fixed as of recent commit, but related issue: 

If if cursor is on 25% on plot A, user goes down to 25% on plot B. No problem. 

But, what if user is on min on plot A, and there is no min on plot B? Current fix is to just go to start, but with some effort we could try to find the closest location to current. Like, instead of min on plot B, go to 25% on B.

**Comment by jooyoungseo** [comment]
@ellvix  -- I like the current idea: focusing on the first element when there is no equivalent stat found in the next group.
