### ISSUE TITLE
speed increase not working on Segmented class

### ISSUE THREAD

**Issue by ellvix** [xability/maidr-legacy#268]

**Comment by yujuny2** [comment]
@ellvix I've actually included the autoplay speed section in the segmented class. This happened because of the interval (which is set to 10 initially, I changed it to 20 now), and the number of times you need to press the period key to get the speed you want depending on the number of data points. The interval is set to be smaller, so that the user has a larger freedom of finding the ideal speed they want (I just thought that if it is set to be big, it might be too fast or too slow between two consecutive speed.) So, in this case, it works, it's just that you have to press multiple times before getting an obvious speedup.

**Comment by yujuny2** [comment]
@ellvix Tell me if you all want to have different interval adjustment for every graph. I'll fix it.
