### ISSUE TITLE
ci: fail on husky

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#374]
The semantic-release has failed. It may have to do with some changes that @sandeep-psintroduced in the husky in the latest PR. Please check the logs and fix the issue: https://github.com/uiuc-ischool-accessible-computing-lab/maidr/actions/runs/7704246863/job/20996187958

**Comment by sandeep-ps** [comment]
Thanks for bringing this to my attention. The only change introduced to Husky in the previous PR was to make it executable (file permissions). 

After going through the build logs, the error is not related to that but to the commit message length. From the stack trace, it looks like this is caused by the squash commit message, "Replaced elements with selector in documentation and examples to conform to the latest maidr json schema spec" and the error is that "footer's lines must not be longer than 100 characters". This would not have been captured by Husky's pre-commit since this is the final commit before the merge using squash commit, not one that's pushed from the development machine. I will try to fix this as soon as possible.

I think we need to enable builds when the PR is opened so that some of the errors like these can be captured before merging. I'm not sure if this particular error would have been caught, as it happens right at the time of merging.
