### ISSUE TITLE
Add ctrl+home and Ctrl+end key commands

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#52]
Also CC'ing @ellvix

We need Ctrl+Home key for going to the very first element and Ctrl+End key for going to the very last element in graphs. This is useful for two-dimensional graphs, such as heatmap and boxplot. However, please make these keys work for other types of graphs including barplot and scatterplot as a general solution. I know, in barplot and scatterplot, these keys' behaviors would be exactly the same as Ctrl+LeftArrow and Ctrl+RightArrow, but we need to make this generalizable so that we can be prepared for any types of graphs going forward.

**Comment by yujuny2** [comment]
I have added this feature to both heatmap and barplot, but not boxplot. I'm not sure which part of the plot should be the first and last element. 

I also wonder if it's okay to add command key for Mac users because command key is similar to ctrl key for Windows. And also ctrl key is commonly used by Mac users for some functions (e.g. ctrl+left/right arrows are used to slide between different windows on mac).

**Comment by ellvix** [comment]
Do we want this? @jooyoungseo as you said users can currently just do Ctrl + Left then Ctrl + Up for the same behavior. And worse yet, it interferes with standard browser controls for switching tabs. Ctrl + Page Up or Down is move left or right a tab.

**Comment by jooyoungseo** [comment]
@yujuny2 -- As we discussed today, we want to conditionally assign navigation keys depending on user agent platform. for Windows and Linux, we can use ctrl keys; for Mac, we need to swap it with CMD key. This platform-dependent keys need to be bound to user help menu (H) key table.

**Comment by jooyoungseo** [comment]
Related to #62

**Comment by yujuny2** [comment]
Added this feature for boxplot too.
