### ISSUE TITLE
fix: address an issue where data navigation does not stop at the end of the last point

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#554]
# Bug Report

## Description

Pressing either LeftArrow at the far left point or RightArrow at the far right point should not trigger any navigation event to indicate their ending point. However, currently, the navigation is triggered even beyond the boundary, making users confused.

This issue can be found in any other plots only except for the line plots.

## Steps to Reproduce

1. Go to https://xabilitylab.ischool.illinois.edu/maidr/galleries/index.html
2. Open a simple bar plot
3. Tab to the plot area
4. Press ctrl+LeftArrow to go to the far left
5. Press LeftArrow

## Actual Behavior

It triggers sonification and text announcement

## Expected Behavior

Nothing needs to be announced

## Screenshots

N/A

## Environment

Universal issue

## Additional Information

N/A

**Comment by ellvix** [comment]
We did this intentionally. We had a talk about it and everything. I agree that this is better though and am happy to change. 

If we do this after typescript I think it'll be much faster / easier.

**Comment by jooyoungseo** [comment]
@ellvix -- Sorry. I don't get it:

Q1: What do we have a different behavior in line plots then?

Q2: Is there any special reason that I could've missed why we do not prevent Sonification and Text from being triggered beyond far left/right? I like the previous behavior better: making them silent when users try to go beyond the boundaries.

**Comment by saaivenk** [comment]
I agree with @ellvix in this. Sighted users have visual feedback (provided highlighting is supported) to know whether they have reached the end of the plot or not. BLV users would have a hard time knowing whether the plot has reached the end or whether it is a bug to display nothing. As human beings, we rely heavily on the feedback of the system we are interacting with to have the best user experience. I'm not sure how the current implementation shows the edge, but I believe differentiating with null/error sound and text would be really helpful in improving the user experience. Even sighted people would never know where they are currently with the plot if highlighting is not supported. For small plots, they might try to coincide the values with the chart. But for massive plots, even sighted users will suffer.

**Comment by jooyoungseo** [comment]
I think we have miscommunication between us here. @SaaiVenkat Please check [line plot](https://xabilitylab.ischool.illinois.edu/maidr/galleries/lineplot.html). And press LeftArrow at the end of far left point. You will hear nothing. This is the expected behavior and standard accepted by other accessible plot libraries. Try this with other plots, such as [bar plot](https://xabilitylab.ischool.illinois.edu/maidr/galleries/bar_plot.html). Bar plot plays tone if you press LeftArrow at the far left point. This bug was introduced sometime (I don't know when it was), but it is definitely an inadvertent regression that we need to fix.

**Comment by jooyoungseo** [comment]
CC @krishnanand5

**Comment by saaivenk** [comment]
I don't have access to the system right now, but I'll check it once I have the access. Based on your description, I agree that we shouldn't play the same point at the end. However, I believe that playing a null tone to let the user know that they have reached the end of the plot and they cannot move beyond this would make the user experience much better. This would further improve the standards of accessible plots. This is like playing an okay tone in ChatLLM after the waiting tone.

**Comment by jooyoungseo** [comment]
@SaaiVenkat -- Great point. However, we need to avoid using the NULL tone to semantically differentiate between NULL and ending point sound.

Also, when introducing the new tone for the ending points, we need to announce text like "Ending point" something like that.

**Comment by jooyoungseo** [comment]
Personally, I am not fully convinced because screen reader users hear nothing in document where no cursor is available. Say, if you keep pressing LeftArrow in NotePad or MS Word with screen reader, you hear nothing once you reach the boundary.

**Comment by saaivenk** [comment]
I get your point. There are two things
1. Visual users can see the cursor at all times, making them be aware of their boundaries. But we can have plots which don't support highlighting, and all the modes we have are configurable. So, there isn't a single standard feedback when the user tried to go out of boundaries. 
2. For BLV users, text editors like MS word and Notepad are well-known environments. There is a high chance that they encountered one at some point and might even be using one on a daily basis. Also, whatever be the editor, the interface for text are not going to change. Even if they switch from notepad to ms word, they have the same interface. However, we are trying to make an uncommon interface (chart) accessible. Users wouldn't have dealt with this structure on a daily basis. Also, we have several sub-categories like boxplot, heatmap, etc whose interface and usage differs. So, users have to create different mappings in their mind. Giving a uniform interface to handle all these cases requires a standard feedback. 

I just mentioned using the NULL point to demonstrate. We should use a completely different sound for this. 

If you think this might annoy rather than improve the user experience, we can just skip it.

**Comment by jooyoungseo** [comment]
@SaaiVenkat -- You've convinced me. Let's provide the edge point feedback. We need to design the sound though.
