### ISSUE TITLE
Scatterplot: autoplay does not kill the previous instance

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#77]
## Reproducible Steps

1. Open scatterplot.html.

1. Focus in the graph area.

1. Hit page-up key to go to the second layer (the smoothed line).

1. Press Ctrl+Shift+Left-Arrow to autoplay.

1. While the autoplay is working, press Ctrl+Shift+Right-Arrow to play the other direction: two autoplays get played at the same time.

## Expected Behavior

The last autoplay needs to kill the previous autoplay job.

**Comment by jooyoungseo** [comment]
@ellvix -- I have tested the latest commit in scatterplot.html and have found the following issue:

1. In the first (point) layer, press Ctrl+LeftArrow to go to the far left item.

1. PageUp to move to the second (line) layer.

1. Press Ctrl+Shift+RightArrow multiple times: sometimes you only hear incomplete parts of the whole play.

**Comment by ellvix** [comment]
I got it!

This was an interesting issue actually. All our audio has a build in `setTimeout` that disconnects the audio when it's done. Good for proper memory usage. The issue was that it was using a global `setTimeout`, and so you'd start a 2nd audio run before the first was done, and you'd still be on the timer from the first. I think.

At any rate, logging the id and using it to do a `clearTimeout` when resetting the smooth audio fixed it. Hooray!
